### ISSUE TITLE
Issue with PyYAML dependancy

### ISSUE THREAD

**Issue by capelry** [neka-nat/kinpy#19]
Hey, I'm trying to use your library to do calculations with a URDF file and I can't actually install it due to the PyYAML library failing during "getting requirements to build wheel" step which only seems to occur for PyYAML 5.4.1, and as far as I can tell kinpy somehow forces use of that version when installing it which causes it to fail (other versions of PyYAML install successfully.
I'm not super familiar with wheel files and pip so if there's an obvious solution apologies

**Comment by neka-nat** [comment]
* { font-size: 13px; font-family: 'MS Pゴシック', sans-serif;}p, ul, ol, blockquote { margin: 0;}a { color: #0064c8; text-decoration: none;}a:hover { color: #0057af; text-decoration: underline;}a:active { color: #004c98;}
Thanks for the report!

I have updated pyyaml and you can try installing it again.




----- Original Message -----




From: "capelry" ***@***.***>

To: "neka-nat/kinpy" ***@***.***>

Cc: "Subscribed" ***@***.***>

Date: 2023/09/14 木 13:45

Subject: [neka-nat/kinpy] Issue with PyYAML dependancy (Issue #19)







Hey, I'm trying to use your library to do calculations with a URDF file and I can't actually install it due to the PyYAML library failing during "getting requirements to build wheel" step which only seems to occur for PyYAML 5.4.1, and as far as I can tell kinpy somehow forces use of that version when installing it which causes it to fail (other versions of PyYAML install successfully.

 I'm not super familiar with wheel files and pip so if there's an obvious solution apologies

**Comment by capelry** [comment]
Thanks for the help, installed and working. Cheers mate!
